name: DsStorage-Nugets

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  gh-version: 1.0.${GITHUB_RUN_NUMBER}
  IMAGE_NAME: ds-storage-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/dibrysoft/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
          
      - run: dotnet build DsStorage.ApiClient/DsStorage.ApiClient.csproj --configuration Release /p:Version=${{ env.gh-version }}
      - name: Create the package
        run: dotnet pack DsStorage.ApiClient/DsStorage.ApiClient.csproj --configuration Release /p:Version=${{ env.gh-version }}
      - name: Publish to github
        run: dotnet nuget push DsStorage.ApiClient/bin/Release/*.nupkg  -k ${{ secrets.GH_TOKEN }} -s https://nuget.pkg.github.com/DibrySoft/index.json --skip-duplicate

  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.105'
        source-url: https://nuget.pkg.github.com/dibrysoft/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
    - name: Build image
      run: |
        dotnet new globaljson --sdk-version 8.0.105 --force
        dotnet publish DsStorage.Api --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release
    - name: Push image
      run: |
        docker login --username=${{secrets.GH_USERNAME}} --password="${{secrets.GH_TOKEN}}" ghcr.io
        docker image tag ${{ env.IMAGE_NAME }}:latest ghcr.io/dibrysoft/${{ env.IMAGE_NAME }}:${{ env.gh-version }}
        docker image tag ${{ env.IMAGE_NAME }}:latest ghcr.io/dibrysoft/${{ env.IMAGE_NAME }}:latest
        docker image push ghcr.io/dibrysoft/${{ env.IMAGE_NAME }}:${{ env.gh-version }}
        docker image push ghcr.io/dibrysoft/${{ env.IMAGE_NAME }}:latest